### PR TITLE
Don't create unnecessary temporary arrays

### PR DESCRIPTION
**Pull request by jlgrall**
Better not to create lots of arrays when many events are emitted. It puts pressure on the garbage collector.

As a bonus, it makes your minified code shorter:
Before: [ Gzip size: 249, Size: 354 ]
After this commit: [ Gzip size: 245, Size: 349 ]

Edit: It is not very important, but in your non-minified file, I think you should really put semicolons at the end of the instructions. It won't change the resulting size of the minified file, and it will make make the code easier to read (especially for people discovering it), easier to jshint and less prone to errors when concatenated with other scripts.

### CODE REVIEW

**Comment by allouis** [comment]
This looks great, awesome stuff man :100: 

As for the lack of semi colons in non-minified file, originally I was minifying by hand, and this just made things easier, but you're right, hopefully sometime I'll get round to fixing that.

It's late here, so I'll double check the code in the morning and merge :+1:

**Comment by jlgrall** [comment]
After this loop simplification: [ Gzip size: 243, Size: 347 ]

**Comment by jlgrall** [comment]
After "Store func and ctx in arrays": [ Gzip size: 241, Size: 346 ]

Also array access is usually faster than property access :)

**Comment by jlgrall** [comment]
That's all for now.
By the way, I really like how you minified the 3 possible different calls to .off(). It is very smart. I couldn't find a shorter way :)

**Comment by allouis** [comment]
Thanks! haha, yeah that took a few iterations to get down that small!

Export header was custom rolled to be as soon as possible, I may release it as a separate repo now you say that though.

**Pull request merged**
