### PR TITLE
Add compatibility for AMD module loading

### PR DESCRIPTION
**Pull request by Aestek**
Now supports :
* Global scope
* Node
* *AMD*

### CODE REVIEW

**Comment by allouis** [comment]
Hey nice work, Only problem I have with this is that it substantially increases the footprint of the code. I was thinking of adding a build script that would generate 3 files, one for AMD, one for CommonJS and one for browser global. If you'd like to PR that's i'd be happy to accept it, If not i'll try get round to it over the next few days. Thanks very much for the PR and sorry it's taken me a while to get back to you. :relaxed:

**Comment by Aestek** [comment]
No promises here, but i'll try to take some time to do that.

**Comment by allouis** [comment]
Thanks, appreciate it, will leave this open for reference for the next PR (whether it comes me or you)

**Comment by Aestek** [comment]
Keeping is as tiny as possible ;)
(Force pushed the branch)

**Comment by allouis** [comment]
Ah this is awesome!

I'd just ask that you update the main fields in the `package.json` and `bower.json` so as to make the transition for people as seamless as possible.

Thank you so much!

**Comment by Aestek** [comment]
All done :)

**Comment by Aestek** [comment]
Added a commit that reduces the lib size too. Can propose it in another PR if you want but since it is based on this one I did not bother doing it.

**Comment by allouis** [comment]
Nice, file size drop as well, winning :blush: 

Just one comment, other than that LGTM :+1:

**Comment by Aestek** [comment]
All good

**Comment by allouis** [comment]
@Aestek Thanks for this :blush:

**Comment by Aestek** [comment]
Np man

**Pull request merged**
