### PR TITLE
on, off and emit now returns target

### PR DESCRIPTION
**Pull request by Amareis**
Just some enhancements. This is important for my purposes and can be useful to someone else.

### CODE REVIEW

**Comment by LucaT1** [comment]
So that you can chain them? Something like promises?

**Comment by Amareis** [comment]
Yes. If you added mixin to Promise, returned from some method, you can chain `on` method and `then`. This used in my [library](https://github.com/Amareis/another-rest-client)

> Also, returns by `get`, `post`, `put`, `patch` and `delete` `Promise` objects also emit these events, but only for current request.
```js
api.dogs(1337).toys.get().on('success', console.log.bind.(console)).then((toys) => "..."); //in log will be xhr instance
api.dogs(1337).toys.get().then((toys) => "..."); //log is clear
```

**Comment by allouis** [comment]
Hi @Amareis thank you for contributing! I will check these changes out now

**Comment by allouis** [comment]
@Amareis Looks like a good change. Thanks for writing tests too! Can you please modify your commit so that you don't touch the package.json file?

**Comment by Amareis** [comment]
@allouis done.

**Comment by allouis** [comment]
@Amareis That's published to npm as version 2.2.0 🎉  Thanks for your contribution

**Comment by Amareis** [comment]
@allouis thank you!

**Pull request merged**
